name 'delivery-cli-install'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures delivery-cli-install'
long_description 'Installs/Configures delivery-cli-install'
version '0.1.0'

depends 'packagecloud'
depends 'build-essential'